# Generated by Django 5.1.2 on 2024-10-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_facebook_url_alter_event_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
