# Generated by Django 5.1.2 on 2024-11-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_event_terms_and_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeuser",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="attendeeuser",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
