# Generated by Django 5.1.2 on 2024-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_attendeeuser_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
