# Generated by Django 5.1.2 on 2024-11-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_attendeeuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
