# Generated by Django 5.1.2 on 2024-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_comment_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeuser',
            name='email_verification_token_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendeeuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
