# Generated by Django 5.1.2 on 2024-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_delete_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
    ]
