# Generated by Django 5.1.2 on 2024-11-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_ticket_api_ticket_ticket__f596c7_idx_and_more'),
        ('api', '0015_event_is_verified_event_verification_status'),
    ]

    operations = [
    ]
