# Generated by Django 5.1.2 on 2024-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_merge_20241112_2129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status_registeration",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed"), ("FULL", "Full")],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
