# Generated by Django 5.1.2 on 2024-11-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_event_status_registeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], default=None, max_length=50, null=True),
        ),
    ]
