# Generated by Django 5.1.2 on 2024-11-20 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_like_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendee',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
