# Generated by Django 5.1.2 on 2024-11-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_event_max_attendee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_attendee",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
