# Generated by Django 5.1.2 on 2024-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_event_max_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_url',
            field=models.URLField(blank=True, help_text='Other social media URL. Separated by comma eg. https://www.example.com, https://www.example2.com', max_length=1000, null=True),
        ),
    ]
